eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

spring:
  application:
    name: microservice-email
  sendgrid:
    api-key:

application:
  requester:
    email:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8082
